apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blog
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: blog
  source:
    repoURL: ssh://git@ssh.git.home.mhlg.io/matehal/blog.git
    targetRevision: main
    path: charts/blog
    helm:
      releaseName: blog
  destination:
    server: https://kubernetes.default.svc
    namespace: blog
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
