apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: blog
  namespace: argocd
spec:
  description: Astro blog deployment
  sourceRepos:
    - ssh://git@ssh.git.home.mhlg.io/matehal/blog.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: blog
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
